### PR TITLE
Revised Issue #9 Added Account Edit Fragment and use POJO in controller

### PR DESCRIPTION
**Pull request by krishnarb3**

### CODE REVIEW

**Comment by krishnarb3** [comment]
Revised #9 
I have made the discussed changes.

-> MenuActivity 
    >Added EventBus onUiEventRecieved for editing user account in fragment
    >Added onBackPressed for fragment transaction from edit account fragment to display account fragment

->AccountEditFieldAdapter
    >Not display error in editText when email is valid 
    >EdittextListener doesnt listen for fields other than Email

->UiEvent : added new UiEvent USER_ACCOUNT_EDIT
->Changed from EditAccount Activity to AccountEditFragment
->Account Fragment : on clicking edit button post UiEvent USER_ACCOUNT_EDIT to EventBus

->Increment recyclerView Library dependency to v7.23.1.1
    >Causes Bugs (MotionEvent causes NullPointerException) otherwise

@ArazAbishov :  Please acknowledge if there are any changes to be made.

**Comment by arazabishov** [comment]
@krishnarb3 Hi Krishna, I will review your changes as soon as possible and will publish feedback here.

**Comment by krishnarb3** [comment]
@ArazAbishov  Thank you , Sir

**Comment by krishnarb3** [comment]
@ArazAbishov 
I have added a new commit with working Account Manager
Solves Issue #10 
Basic testing of Account Manager done , extensive testing ongoing to prevent bugs.

**Comment by krishnarb3** [comment]
Please review the code and suggest changes.
Thank you.

**Comment by arazabishov** [comment]
Hi @krishnarb3, 

We are currently working on completely new version of dashboard app based on DHIS 2 android SDK. SDK itself already contains profile fragment implementation which we are planning to re-use in dashboard app as well. 

What we can do is to take some bits and pieces of your implementation which can complete SDK's profile fragment (you can also do this if you want). I recommend you to take a look into https://github.com/dhis2/dhis2-android-eventcapture repository in order to get better understanding of what we have already done. 

Thanks a lot for you contribution!

**Pull request closed without merging**
