### PR TITLE
Issue #3 fixed.

### PR DESCRIPTION
**Pull request by NateshR**
ViewPager observe changes now on adding and deleting dashboards.
FragmentStatePageAdapter implemented.
Smooth scroll to the added or removed dashboard.
onLoadFinished in DashboardViewPagerFragment is called twice and it is necessary to be called twice, first when saved dashboard locally and second when synced from server. But reflecting added or removed dashboard is called once only, the second time it just updates the data in DashboardAdapter.

### CODE REVIEW

**Comment by NateshR** [comment]
Issue #1 fixed.

**Comment by arazabishov** [comment]
Hi @NateshR,

Thank you for contribution. Some comments regarding pull-request:
- changes in dashboards table should be pushed through ContentProvider mechanism, not EventBus.
- pull-request is huge (touches too many files).

Could you please adjust it according to comments and re-submit?

Thanks.

**Comment by NateshR** [comment]
Event bus is used to notify only. let me send another pull request, no idea why it's showing so many files.

**Comment by NateshR** [comment]
I was comparing it with master, that's why it was showing 301 files changed.

**Comment by NateshR** [comment]
New pull request for this #30

**Comment by arazabishov** [comment]
@NateshR Closing this pull-request in favor of https://github.com/dhis2/dhis2-android-dashboard/pull/30

**Pull request closed without merging**
